language: ruby
rvm:
  - ruby-2.2.5
  - ruby-2.3.3
  - ruby-head
  - rubinius-3.62
  - jruby-9.1.5.0
  - jruby-head
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y openssl libssl-dev
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
sudo: required
dist: trusty
